### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by HaveF** [johnf/github-issue-importer#7]
thanks your #5, I can import some issues, but still cannot get all things to work.

```
Processing Bug 1022140
Processing Bug 1041906
Processing Bug 1260415
Processing Bug 555014
Processing Bug 613153
Processing Bug 869098
Processing Bug 914221
Processing Bug 969391
Processing Bug 1028986
Processing Bug 1090950
Processing Bug 1193820
Processing Bug 1228099
Processing Bug 1228457
Processing Bug 1228458
Processing Bug 1232977
Processing Bug 1240786
Processing Bug 1242979
Processing Bug 1243855
Processing Bug 1245066
Processing Bug 1245111
Processing Bug 1245535
Processing Bug 1245616
Processing Bug 1247266
Processing Bug 1247270
Processing Bug 1250335
/usr/lib/ruby/1.9.1/net/protocol.rb:146:in `rescue in rbuf_fill': Timeout::Error (Faraday::TimeoutError)
    from /usr/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
    from /usr/lib/ruby/1.9.1/net/protocol.rb:92:in `read'
    from /usr/lib/ruby/1.9.1/net/http.rb:2756:in `read_body_0'
    from /usr/lib/ruby/1.9.1/net/http.rb:2711:in `read_body'
    from /usr/lib/ruby/1.9.1/net/http.rb:2736:in `body'
    from /usr/lib/ruby/1.9.1/net/http.rb:2673:in `reading_body'
    from /usr/lib/ruby/1.9.1/net/http.rb:1322:in `block in transport_request'
    from /usr/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
    from /usr/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
    from /usr/lib/ruby/1.9.1/net/http.rb:1294:in `request'
    from /usr/lib/ruby/1.9.1/net/http.rb:1287:in `block in request'
    from /usr/lib/ruby/1.9.1/net/http.rb:746:in `start'
    from /usr/lib/ruby/1.9.1/net/http.rb:1285:in `request'
    from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
    from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:39:in `call'
    from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
    from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
    from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
    from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
    from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'
    from /var/lib/gems/1.9.1/gems/sawyer-0.5.3/lib/sawyer/agent.rb:94:in `call'
    from /var/lib/gems/1.9.1/gems/octokit-2.7.1/lib/octokit/client.rb:257:in `request'
    from /var/lib/gems/1.9.1/gems/octokit-2.7.1/lib/octokit/client.rb:138:in `post'
    from /var/lib/gems/1.9.1/gems/octokit-2.7.1/lib/octokit/client/issues.rb:100:in `create_issue'
    from /var/lib/gems/1.9.1/gems/github-issue-importer-0.0.3/bin/github-issue-importer:87:in `block in <top (required)>'
    from /var/lib/gems/1.9.1/gems/github-issue-importer-0.0.3/bin/github-issue-importer:68:in `each'
    from /var/lib/gems/1.9.1/gems/github-issue-importer-0.0.3/bin/github-issue-importer:68:in `<top (required)>'
    from /usr/local/bin/github-issue-importer:23:in `load'
    from /usr/local/bin/github-issue-importer:23:in `<main>'

```

last time, I send you my token and command line....

**Comment by johnf** [comment]
Closing some really old bugs, please reopen if still an issue
